plugins {
    id 'com.android.application'
}

android {
    namespace 'com.systempro.app'
    compileSdk 34

    defaultConfig {
        applicationId "com.systempro.faisal"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
        
        setProperty("archivesBaseName", "System-Pro-Master")
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    // یہ حصہ آپ کی فائلز کو خودکار طریقے سے لنک کرے گا
    sourceSets {
        main {
            assets.srcDirs = ['src/main/assets']
            res.srcDirs = ['src/main/res']
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
}
